### ISSUE TITLE
Assignment of error results

### ISSUE THREAD

**Issue by marius-posa** [RobWHickman/MATisse#2]
Finalisation error show as no-fixation error in the compact results table

**Comment by RobWHickman** [comment]
simplest way to solve would be to implement a sort to the trial_results before vertcat-ing them. unfortunately matlab doesn't like sorts on structs but I'll see what I can do

**Comment by RobWHickman** [comment]
currently there is also an error for the binary choice task where the monkey does start to bid but lands outside of both halves. Set as 'undefined error' for now

**Comment by RobWHickman** [comment]
should be working now- though does give two errors when monkey makes them at same time
